package com.bikerental.bikerental;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderInfoResponse implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OrderInfoResponse() {
    }




}