package com.bikerental.bikerental;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReturnedBike implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ReturnedBike() {
    }




}