package com.bikerental.bikerental;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class TerminateSubscriptionResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("Info")
	private java.lang.String info;

	public TerminateSubscriptionResponse() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getInfo() {
		return this.info;
	}

	public void setInfo(java.lang.String info) {
		this.info = info;
	}

	public TerminateSubscriptionResponse(java.lang.String status,
			java.lang.String info) {
		this.status = status;
		this.info = info;
	}

}