package com.bikerental.bikerental;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class VerifyUserResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Verified")
	private java.lang.Boolean verified;

	@org.kie.api.definition.type.Label("Info")
	private java.lang.String info;

	public VerifyUserResponse() {
	}

	public java.lang.Boolean getVerified() {
		return this.verified;
	}

	public void setVerified(java.lang.Boolean verified) {
		this.verified = verified;
	}

	public java.lang.String getInfo() {
		return this.info;
	}

	public void setInfo(java.lang.String info) {
		this.info = info;
	}

	public VerifyUserResponse(java.lang.Boolean verified, java.lang.String info) {
		this.verified = verified;
		this.info = info;
	}

}