package com.bikerental.bikerental;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VerifyUserResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Verified")
	private java.lang.Boolean verified;

	public VerifyUserResponse() {
	}

	public java.lang.Boolean getVerified() {
		return this.verified;
	}

	public void setVerified(java.lang.Boolean verified) {
		this.verified = verified;
	}

	public VerifyUserResponse(java.lang.Boolean verified) {
		this.verified = verified;
	}

}